blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingListView, \
    MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, MainPage, MailingAttemptListView

app_name = "mailing"

urlpatterns = [
    path("", cache_page(5)(MainPage.as_view()), name="index"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailings/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailings/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path(
        "mailings/<int:mailing_id>/attempts/",
        MailingAttemptListView.as_view(),
        name="mailing_attempt_list",
    ),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Client(models.Model):
    full_name = models.CharField(verbose_name="Ф.И.О клиента", max_length=255)
    email = models.EmailField(verbose_name="e-mail адрес", unique=True)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="clients", **NULLABLE
    )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=100, verbose_name="Тема сообщения")
    body = models.TextField(verbose_name="Сообщение")
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="messages", **NULLABLE
    )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("created", "Создана"),
        ("started", "Активна"),
        ("completed", "Завершена"),
        ("disabled", "Отключить"),
    ]

    PERIODICITY_CHOICES = [
        ("daily", "Ежедневно"),
        ("weekly", "Еженедельно"),
        ("monthly", "Ежемесячно"),
    ]

    description = models.CharField(
        verbose_name="описание", max_length=255, **NULLABLE
    )
    start_time = models.DateTimeField(auto_now=True, verbose_name="дата начала рассылки")
    periodicity = models.CharField(
        verbose_name="периодичность", max_length=10, choices=PERIODICITY_CHOICES
    )
    status = models.CharField(
        verbose_name="статус", max_length=10, choices=STATUS_CHOICES, default="created"
    )
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, verbose_name="сообщение"
    )
    clients = models.ManyToManyField(Client, verbose_name="клиенты")
    actual_end_time = models.DateTimeField(
        verbose_name="дата завершения рассылки", blank=True, null=True
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="mailings", **NULLABLE
    )

    def __str__(self):
        return f"Mailing {self.id} - {self.status}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ("can_deactivate_mailing", 'Can deactivate mailing'),
        ]


class MailingAttempt(models.Model):
    STATUS_CHOICES = [("success", "Успешно"), ("failed", "Не успешно")]

    mailing = models.ForeignKey(
        Mailing, on_delete=models.CASCADE, verbose_name='Рассылка'
    )
    send_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE)

    def __str__(self):
        return f"Попытка {self.id} для рассылки {self.mailing.id}"

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

mailing/forms.py
from django.forms import BooleanField, ModelForm

from mailing.models import Client, Message, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("owner",)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("owner",)


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("owner",)


class MailingManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ("status",)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import ClientForm, MessageForm, MailingForm, MailingManagerForm
from mailing.models import Client, Message, Mailing, MailingAttempt
from mailing.services import get_cached_articles


class MainPage(View):
    """Выводит статистику"""
    def get(self, request, *args, **kwargs):
        total_mailings = Mailing.objects.count()
        active_mailings = Mailing.objects.filter(status="started").count()
        unique_clients_count = Client.objects.distinct().count()

        random_articles = get_cached_articles()

        context = {
            "total_mailings": total_mailings,
            "active_mailings": active_mailings,
            "unique_clients_count": unique_clients_count,
            "random_articles": random_articles,
        }

        return render(request, "mailing/index.html", context)


# CRUD для клиентов
class ClientListView(ListView):
    model = Client
    template_name = "mailing/client_list.html"
    context_object_name = "clients"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                # Если пользователь администратор, показать всех клиентов
                return Client.objects.all()
            else:
                # Иначе показать клиентов, связанных с текущим пользователем
                return Client.objects.filter(owner=self.request.user)
        else:
            # Если пользователь не аутентифицирован, показать всех клиентов
            return Client.objects.all()


class ClientDetailView(DetailView):
    model = Client
    template_name = "mailing/client_detail.html"


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def form_valid(self, form):
        # фун-ция по созданию клиента только авторизаванных пользователей
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")


class ClientDeleteView(DeleteView):
    model = Client
    template_name = "mailing/client_confirm_delete.html"
    success_url = reverse_lazy("mailing:client_list")


# CRUD для сообщений
class MessageListView(ListView):
    model = Message
    template_name = "mailing/message_list.html"
    context_object_name = "messages"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                # Если пользователь администратор, показать все сообщения
                return Message.objects.all()
            else:
                # Иначе показать сообщения, связанных с текущим пользователем
                return Message.objects.filter(owner=self.request.user)
        else:
            # Если пользователь не аутентифицирован, показать все сообщения
            return Message.objects.all()


class MessageDetailView(DetailView):
    model = Message
    template_name = "mailing/message_detail.html"


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        # фун-ция по созданию сообщения только авторизаванных пользователей
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class MessageDeleteView(DeleteView):
    model = Message
    template_name = "mailing/message_confirm_delete.html"
    success_url = reverse_lazy("mailing:message_list")


# CRUD для рассылки
class MailingListView(ListView):
    model = Mailing
    template_name = "mailing/mailing_list.html"
    context_object_name = "mailings"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser or self.request.user.groups.filter(name='managers').exists():
                # Если пользователь администратор или менеджер, показать все рассылки
                return Mailing.objects.all()
            else:
                # Иначе показать рассылки, связанные с текущим пользователем
                return Mailing.objects.filter(owner=self.request.user)
        else:
            # Если пользователь не аутентифицирован, показать все рассылки
            return Mailing.objects.all()


class MailingDetailView(DetailView):
    model = Mailing
    template_name = "mailing/mailing_detail.html"


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        # фун-ция по созданию рассылки только авторизаванных пользователей
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def get_form_class(self):
        user = self.request.user
        # Проверка, является ли пользователь суперпользователем
        if user.is_superuser:
            return MailingForm

        # Проверка, является ли пользователь владельцем объекта
        if user == self.object.owner:
            return MailingForm

        # Проверка наличия разрешения на деактивацию рассылки
        if user.has_perm("mailing.can_deactivate_mailing"):
            return MailingManagerForm

        raise PermissionDenied


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = "mailing/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = "mailing/mailing_attempt_list.html"
    context_object_name = "attempts"

    def get_queryset(self):
        mailing_id = self.kwargs["mailing_id"]
        return MailingAttempt.objects.filter(mailing_id=mailing_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_id = self.kwargs["mailing_id"]
        context["mailing"] = get_object_or_404(Mailing, pk=mailing_id)
        context["mailing_id"] = mailing_id
        return context

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">

    <link rel="shortcut icon" href="/media/mailing/email.jpg"/>
    <title>Рассылки - </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">
    <style>
        /* CSS styles for the button */

        {#.scroll-to-top:hover {#}
        {#    background-color: #0056b3; /* Darker shade on hover */#}

    </style>
    <style>
        /* CSS to create a sticky footer */
        html, body {
            height: 100%; /* Ensure the body takes full height */
            margin: 0; /* Remove default margin */
        }

        .wrapper {
            display: flex;
            flex-direction: column; /* Arrange children in a column */
            min-height: 100vh; /* Minimum height of 100% of the viewport */
        }

        .content {
            flex: 1; /* Allow content to grow and fill available space */
        }

        footer {
            background-color: #f8f9fa; /* Optional: Background color for the footer */
            border-top: 1px solid #dee2e6; /* Optional: Top border for the footer */
            text-align: center; /* Center text in footer */
            padding: 10px; /* Padding for footer content */
        }
    </style>
</head>


<body style="background-image: url('/static/images/background.jpg'); background-size: cover; background-repeat: no-repeat;">
<div class="wrapper">
    <div class="content">
        <!-- Верхний колонтитул с меню-->
        <header class="p-3 mb-3 bg-dark border-bottom">
            {% include 'mailing/includes/inc_menu.html' %}
        </header>

        <!-- Заголовок -->
        <main class="flex-shrink-0 mb-4">
            <div class="container text-center">
                <h1 class="mt-5"><strong>Рассылки</strong></h1>
                <h4 class="mt-3 mb-5"><strong>Сервис рассылок - это отличный вариант информирования ваших
                    клиентов</strong></h4>
            </div>
        </main>

        <!-- Блок рассылок -->
        {% block content %}
        {% endblock %}
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </div>

    <!-- Нижний колонтитул -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
        <div class="container">

            <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Company, Inc</span>
            </div>

        </div>
    </footer>
</div>

</body>

</html>

mailing/templates/mailing/client_confirm_delete.html
<!-- templates/client_confirm_delete.html -->

{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить клиента "{{ object.full_name }}"?</p>
                                <button type="submit" class="btn btn-success">Подтвердить</button>
                                <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
<!-- templates/client_detail.html -->
{% extends 'mailing/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text"><strong>Клиент: {{ object.full_name }} </strong></p>
                        <p class="card-text">Комментарий: {{ object.comment }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:client_list' %}" 
                                   role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Клиенты</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Ф.И.О.</th>
                <th>Email</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.full_name }}</td>
                    <td>{{ client.email }}</td>
                    <td>
                        <a href="{% url 'mailing:client_detail' client.pk %}"
                           class="btn btn-info btn-sm">Просмотреть</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'mailing:client_update' client.pk %}"
                               class="btn btn-warning btn-sm">Изменить</a>
                            <a href="{% url 'mailing:client_delete' client.pk %}"
                               class="btn btn-danger btn-sm">Удалить</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-6">
            {% if user.is_authenticated %}
                {% if user.is_superuser or not perms.mailing.can_deactivate_mailing %}
                    <a href="{% url 'mailing:client_create' %}" class="btn btn-success">Добавить клиента</a>
                {% endif %}
            {% endif %}
            <a href="{% url 'mailing:index' %}" class="btn btn-primary">На главную</a>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% load static %}

{% block content %}
    <!-- Статистика -->
    <div class="container">
        <div class="statistics">
            <h2>Статистика</h2>
            <div class="stat-item">
                <p><strong>Количество рассылок всего:</strong> {{ total_mailings }}</p>
            </div>
            <div class="stat-item">
                <p><strong>Количество активных рассылок:</strong> {{ active_mailings }}</p>
            </div>
            <div class="stat-item">
                <p><strong>Количество уникальных клиентов для рассылок:</strong> {{ unique_clients_count }}</p>
            </div>
        </div>
    </div>

    <!-- Случайные статьи -->
    <div class="container">
        <div class="random-articles">
            <h2>Случайные статьи</h2>
            <div class="row articles-grid">
                {% if random_articles %}
                    {% for blog in random_articles %}
                        <div class="col-md-3 mb-4"> <!-- Используем класс mb-4 для нижнего отступа -->
                            <div class="card" style="width: 100%;"> <!-- Установлено 100% для ширины карточки -->
                                {% if blog.preview_image %}
                                    <img src="{{ blog.preview_image.url }}" class="card-img-top" alt="{{ blog.title }}">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ blog.title }}</h5>
                                    <p class="card-text">{{ blog.body | truncatechars:100 }}...</p>
                                    <a href="{% url 'blog:view' blog.pk %}" class="btn btn-primary">Читать
                                        полностью</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Нет доступных статей.</p>  <!-- Сообщение, если нет статей -->
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_attempt_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Список попыток рассылки: {{ mailing.description }}</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>№</th>
            <th>Время создания</th>
            <th>Статус</th>
            <th>Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for attempt in attempts %}
            <tr>
                <td>{{ attempt.id }}</td>
                <td>{{ attempt.send_time }}</td>
                <td>{{ attempt.status }}</td>
                <td>{{ attempt.server_response }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">Пока нет попыток рассылок.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="text-center mt-3">
        <a href="{% url 'mailing:mailing_detail' mailing.pk %}" class="btn btn-primary">Назад</a>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
<!-- templates/client_confirm_delete.html -->

{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить рассылку "{{ object.description }}"?</p>
                                <button type="submit" class="btn btn-success">Подтвердить</button>
                                <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row justify-content-start">  <!-- Изменено на justify-content-start -->
                <div class="col-md-6">
                    <div class="card shadow-sm mb-4">  <!-- Добавлен отступ между карточками -->
                        <div class="card-body">
                            <p class="card-text"><strong>Описание рассылки: {{ object.description }} </strong></p>
                            <p class="card-text">Сообщение рассылки: {{ object.message }}</p>
                            <p class="card-text">Статус рассылки: {{ object.status }}</p>
                            <p class="card-text">Дата начала рассылки: {{ object.start_time }}</p>
                            <p class="card-text">Дата окончания рассылки: {{ object.actual_end_time }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}"
                                       role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Дублирование карточки -->
                <div class="col-md-6">
                    <div class="card shadow-sm mb-4">  <!-- Добавлен отступ между карточками -->
                        <div class="card-body">
                            <p class="card-text"><strong>История рассылки</strong></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'mailing:mailing_attempt_list' mailing.pk %}"
                                       role="button">Перейти</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if mailing %}
                                <button type="submit" class="btn btn-success">Редактировать</button>
                            {% else %}
                                <button type="submit" class="btn btn-success">Создать</button>
                            {% endif %}
                            <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button">Назад</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Список рассылок</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Описание рассылки</th>
                <th>Сообщение рассылки</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for mailing in mailings %}
                <tr>
                    <td>{{ mailing.description }}</td>
                    <td>{{ mailing.message }}</td>
                    <td>
                        <a href="{% url 'mailing:mailing_detail' mailing.pk %}"
                           class="btn btn-info btn-sm">Просмотреть</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'mailing:mailing_update' mailing.pk %}"
                               class="btn btn-warning btn-sm">Изменить</a>
                            {% if user.is_authenticated and user.is_superuser or not perms.mailing.can_deactivate_mailing %}
                                <a href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   class="btn btn-danger btn-sm">Удалить</a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-6">
            {% if user.is_authenticated %}
                {% if user.is_superuser or not perms.mailing.can_deactivate_mailing %}
                    <a href="{% url 'mailing:mailing_create' %}" class="btn btn-success">Создать рассылку</a>
                {% endif %}
            {% endif %}
            <a href="{% url 'mailing:index' %}" class="btn btn-primary">На главную</a>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Список сообщений</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Тема сообщения</th>
                <th>Текст сообщения</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for message in messages %}
                <tr>
                    <td>{{ message.subject }}</td>
                    <td>{{ message.body }}</td>
                    <td>
                        <a href="{% url 'mailing:message_detail' message.pk %}"
                           class="btn btn-info btn-sm">Просмотреть</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'mailing:message_update' message.pk %}"
                               class="btn btn-warning btn-sm">Изменить</a>
                            <a href="{% url 'mailing:message_delete' message.pk %}"
                               class="btn btn-danger btn-sm">Удалить</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="row justify-content-center text-center">
        <div class="col-6">
            {% if user.is_authenticated %}
                {% if user.is_superuser or not perms.mailing.can_deactivate_mailing %}
                    <a href="{% url 'mailing:message_create' %}" class="btn btn-success">Создать сообщение</a>
                {% endif %}
            {% endif %}
            <a href="{% url 'mailing:index' %}" class="btn btn-primary">На главную</a>
        </div>
    </div>
{% endblock %}