blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    body = models.TextField(verbose_name='Содержание')
    preview_image = models.ImageField(upload_to="blog/preview", verbose_name="Изображение превью", **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост в блоге'
        verbose_name_plural = 'Посты в блоге'

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name,  fild in self.fields.items():
            fild.widget.attrs['class'] = 'form-control'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить блог "{{ blog.title }}"?</p>
                                <button type="submit" class="btn btn-success">Подтвердить</button>
                                <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p class="card-text"><strong>Заголовок: {{ blog.title }} ({{ blog.slug }})</strong></p>
                            <p class="card-text">Описание блога: {{ blog.body }}</p>
                            <p class="card-text">Количество просмотров: {{ blog.views_count }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'blog:list' %}"
                                       role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            {% if blog %}
                                <h3 class="card-title">Редактирование блога</h3>
                            {% else %}
                                <h3 class="card-title">Создание блога</h3>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if blog %}
                                <button type="submit" class="btn btn-success">Редактировать</button>
                            {% else %}
                                <button type="submit" class="btn btn-success">Создать</button>
                            {% endif %}
                            <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Назад</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="row mt-4">
        <div class="col-12 text-center">
            {% if user.is_superuser %}
                <a class="btn btn-success btn-lg" href="{% url 'blog:create' %}" role="button">Создать блог</a>
            {% endif %}
        </div>
    </div>
    <div class="album py-5 bg-body-tertiary">

        <div class="container">
            <div class="row">
                {% for blog in blog_list %}
                    <div class="col-6 mb-4">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">{{ blog.title }}</h5>
                                <td>
                                    <a href="{% url 'blog:view' blog.pk %}"
                                       class="btn btn-info btn-sm">Просмотреть</a>
                                    {% if user.is_superuser %}
                                        <a href="{% url 'blog:edit' blog.pk %}"
                                           class=" btn btn-warning btn-sm">Редактировать</a>
                                        <a href="{% url 'blog:delete' blog.pk %}"
                                           class="btn btn-danger btn-sm">Удалить</a>
                                    {% endif %}
                                </td>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}