blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="mailing")),
    path("users/", include("users.urls", namespace="users")),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingListView, \
    MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, MainPage, MailingAttemptListView

app_name = "mailing"

urlpatterns = [
    path("", cache_page(5)(MainPage.as_view()), name="index"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("clients/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "messages/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "messages/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("mailings/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailings/create/", MailingCreateView.as_view(), name="mailing_create"),
    path(
        "mailings/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path(
        "mailings/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path(
        "mailings/<int:mailing_id>/attempts/",
        MailingAttemptListView.as_view(),
        name="mailing_attempt_list",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name="email-confirm"),
    path('password-reset/', reset_password, name='password_reset'),
    path("users/", UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = models.CharField(max_length=35, verbose_name="Телефон", **NULLABLE, help_text="Введите номер телефона")
    country = models.CharField(max_length=150, verbose_name="Страна", help_text="Введите страну проживания")
    avatar = models.ImageField(upload_to="users/avatars/", **NULLABLE, help_text="Загрузите свой аватар")
    token = models.CharField(max_length=100, verbose_name="Token", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", 'Can block users'),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import BooleanField, ModelForm

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = User
        fields = ("is_active",)

users/views.py
import random
import secrets
import string

from django.contrib.auth.hashers import make_password
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserManagerForm
from users.models import User


class UserListView(ListView):
    model = User
    template_name = "users/user_list.html"
    context_object_name = "users"


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        """Метод для отправки ссылки на почту, для её подтверждения """
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет, перейди по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    """ф-ция для верификации токена, и активации пользователя"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.token = None
    user.save()
    return redirect(reverse("users:login"))


def generate_random_password(length=8):
    # Фун-ция кот.генерирует пароль

    # Определяем возможные символы для пароля
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''  # Создаем пустую строку для пароля
    # Генерируем пароль
    for i in range(length):
        random_char = random.choice(characters)  # Выбираем случайный символ
        password += random_char  # Добавляем его к паролю

    return password


def reset_password(request):
    # ф-ция восстановления, пароля зарегистрированного пользователя

    if request.method == 'POST':  # Мы проверяем, является ли метод запроса POST.
        email = request.POST.get('email')  # извлекаем email  из запроса

        try:
            user = User.objects.get(email=email)  # пытаемся получить пользователя по email
            new_password = generate_random_password()  # Генерация нового пароля через ф-цию
            user.password = make_password(new_password)  # Хеширование пароля
            user.save()

            # Отправка нового пароля на электронную почту
            send_mail(
                subject="Ваш новый пароль",
                message=f"Ваш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
                fail_silently=False,
            )
            # Перенаправление на страницу входа после успешного восстановления
            return redirect('users:login')

        # Обработка случая, когда пользователь не найден
        except User.DoesNotExist:
            return render(request, 'users/templates/password_reset.html', {'error': 'Пользователь с таким email не найден.'})
    # Если метод запроса не POST, а GET мы просто отображаем форму для восстановления пароля.
    return render(request, 'users/templates/password_reset.html')


class UserUpdateView(UpdateView):
    model = User
    form_class = UserManagerForm
    success_url = reverse_lazy("users:user_list")

    def get_form_class(self):
        user = self.request.user
        # Проверка наличия разрешения на деактивацию рассылки
        if user.has_perm("users.can_block_user"):
            return UserManagerForm
        raise PermissionDenied

users/templates/users/password_reset.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            <label for="email">Введите ваш email:</label>
                            <input type="email" name="email" required>
                            <button type="submit" class="btn btn-success">Восстановить пароль</button>
                            <a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Назад</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
        {% if error %}
            <p style="color:red;">{{ error }}</p>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                            <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Назад</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Список пользователей</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Почта пользователя</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>
                        {% if perms.users.can_block_user %}
                            <a href="{% url 'users:user_update' user.pk %}"
                               class="btn btn-warning btn-sm">Изменить</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <a href="{% url 'mailing:index' %}" class="btn btn-primary">На главную</a>
    </div>
{% endblock %}